improve publish workflow
- add gates for final and prerelease versions
- configure release according to version type
- verify tag version matches with setup and changelog

diff --git a/.github/workflows/publish-to-pypi.yml b/.github/workflows/publish-to-pypi.yml
--- a/.github/workflows/publish-to-pypi.yml
+++ b/.github/workflows/publish-to-pypi.yml
@@ -1,6 +1,9 @@
 name: Publish Python 🐍 distribution 📦 to PyPI
 
-on: push
+on: 'push'
+
+env:
+  DEFAULT_PYTHON: "3.12"
 
 jobs:
   build:
@@ -12,7 +15,8 @@ jobs:
     - name: Set up Python
       uses: actions/setup-python@v5
       with:
-        python-version: "3.x"
+        python-version: ${{ env.DEFAULT_PYTHON }}
+        check-latest: true
     - name: Install pypa/build
       run: >-
         python3 -m
@@ -26,12 +30,79 @@ jobs:
       with:
         name: python-package-distributions
         path: dist/
+
+  check_version:
+    name: Check the version
+    if: startsWith(github.ref, 'refs/tags/')  # only publish to PyPI on tag pushes
+    needs:
+      - build
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v4
+        with:
+          fetch-depth: 0
+
+      - name: Extract tag version
+        id: extract_tag
+        run: |
+          TAG_VERSION=${GITHUB_REF#refs/tags/}
+          echo "TAG_VERSION=$TAG_VERSION" >> $GITHUB_ENV
+
+      - name: Check tag in setup.cfg
+        run: |
+          if ! grep -q "version = $TAG_VERSION" setup.cfg; then
+            echo "Error: Tag version $TAG_VERSION not found in the setup.cfg."
+            exit 1
+          else
+            echo "Success: Tag version $TAG_VERSION found in setup.cfg."
+          fi
+
+      - name: Check changelog entry
+        run: |
+          if [ github.ref =~ 'refs/tags/[0-9]+\\.[0-9]+\\.[0-9]+$' ]; then
+            if ! grep -q "## $TAG_VERSION" CHANGELOG.md; then
+              echo "No changelog entry found for version $TAG_VERSION."
+              exit 1
+            else
+              echo "Changelog entry found for version $TAG_VERSION."
+            fi
+          else
+            echo "Pre-release tag, skipping changelog check"
+          fi
+
+      - name: Check if version type matches branch type
+        run: |
+          branch=$(git branch -r --contains ${{ github.ref }} --format "%(refname:lstrip=3)")
+          echo "Branch: $branch"
+          version=${GITHUB_REF#refs/tags/}
+          echo "Version from tag: $version"
+
+          # Check if the version is a prerelease
+          if [[ "$version" =~ [a-zA-Z] ]]; then
+            echo "Prerelease version detected: $version"
+            prerelease=true
+          else
+            echo "Final release version detected: $version"
+            prerelease=false
+          fi
+
+          # Fail if it's a prerelease and on the main branch
+          if [[ "$branch" == "main" && "$prerelease" == "true" ]]; then
+            echo "Error: Prerelease versions are not allowed on the main branch."
+            exit 1
+          fi
+
+          # Fail if it's a final release on a non-main branch
+          if [[ "$branch" != "main" && "$prerelease" == "false" ]]; then
+            echo "Error: Final releases are not allowed on non-main branches."
+            exit 1
+          fi
+
   publish-to-pypi:
     name: >-
       Publish Python 🐍 distribution 📦 to PyPI
-    if: startsWith(github.ref, 'refs/tags/')  # only publish to PyPI on tag pushes
-    needs:
-    - build
+    needs: check_version
     runs-on: ubuntu-latest
     environment:
       name: pypi
@@ -46,6 +117,7 @@ jobs:
         path: dist/
     - name: Publish distribution 📦 to PyPI
       uses: pypa/gh-action-pypi-publish@release/v1
+
   github-release:
     name: >-
       Sign the Python 🐍 distribution 📦 with Sigstore
@@ -59,6 +131,23 @@ jobs:
       id-token: write  # IMPORTANT: mandatory for sigstore
 
     steps:
+    - uses: actions/checkout@v4
+      with:
+        fetch-depth: 1
+    - name: Get version
+      id: version
+      run: |
+        TAG_VERSION=${GITHUB_REF#refs/tags/}
+        echo "version=$TAG_VERSION" >> $GITHUB_OUTPUT
+    - name: Check if version is prerelease
+      id: check_prerelease
+      run: |
+        TAG_VERSION="${{ steps.version.outputs.version }}"
+        if [[ "$TAG_VERSION" =~ [a-zA-Z] ]]; then
+          echo "prerelease=true" >> $GITHUB_OUTPUT
+        else
+          echo "prerelease=false" >> $GITHUB_OUTPUT
+        fi
     - name: Download all the dists
       uses: actions/download-artifact@v4
       with:
@@ -70,14 +159,15 @@ jobs:
         inputs: >-
           ./dist/*.tar.gz
           ./dist/*.whl
-    - name: Create GitHub Release
+    - name: Release
+      uses: softprops/action-gh-release@v2
+      with:
+        tag_name: ${{ github.ref }}
+        name: ${{ steps.version.outputs.version }}
+        generate_release_notes: true
+        prerelease: ${{ steps.check_prerelease.outputs.prerelease }}  # Mark as prerelease if necessary
       env:
-        GITHUB_TOKEN: ${{ github.token }}
-      run: >-
-        gh release create
-        '${{ github.ref_name }}'
-        --repo '${{ github.repository }}'
-        --generate-notes
+        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}   
     - name: Upload artifact signatures to GitHub Release
       env:
         GITHUB_TOKEN: ${{ github.token }}
